### PR TITLE
StudentCommands Cog to Slash Commands

### PR DESCRIPTION
**Pull request by NicoleP23**
# Description

Changed ``corgme``, ``helloworld ``, ``ping``, ``poll``, and ``roll`` commands to slash commands in the ``StudentCommands`` cog.

## Issues

Does not close an issue.

## Type of change

Select one or more of the following:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (describe below)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. List any edge cases you tested.
If you come up with any edge cases you didn't test while writing this PR, cancel the PR and test again.

- [ ] Test A
     - run ``-ping`` or any other - command, shouldn't work
- [ ] Test B
       - Run ``-sync`` if commands aren't showing
       - Run ``/ping``
- [ ] Test C
       - Run ``/roll 1d6`` and ``/roll 1d6 +1``
- [ ] Test D
       - Run ``/helloworld`` and ``helloworld`` ``python``
- [ ] Test E
       - Run ``/poll`` ``question?`` ``yes`` ``no`` and ``/poll`` ``question`` ``option one`` ``option two`` ``as many options as you want``
- [ ] Test F
       - Run ``/corgme`` ``/corgme`` ``404`` (or any number)

# Checklist:

- [x] All local commits have been pushed to remote
- [x] All changes on the base branch have been merged into this branch, either by rebase or merge
- [x] My code is [PEP-8](https://pep8.org/) compliant (excluding maximum line length, keep that to 100ish characters)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added [Google Docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) for all new functions/methods
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by NicoleP23** [comment]
Merged development branch into this branch, no merge conflicts, checked with a diff report, and re-tested using above tests. Ready to be reviewed. :+1:

**Comment by ReginPotter** [comment]
Please fix reactions on the `poll` command

**Review by ReginPotter — CHANGES_REQUESTED** [review]
Please fix reactions to the `poll` command

**Review by ReginPotter — APPROVED** [review]
looks good, request changes have been added. Ready to merge

**Pull request merged**
